### ISSUE TITLE
multiple anon.session and db file creation 

### ISSUE THREAD

**Issue by codewarnab** [FujiwaraChoki/TeleSync#5]
When running the `run.sh` script from different folders, it creates `anon.session` and `db` files in those folders. This behavior requires repeated login sessions each time the script is run from a new location, which is inconvenient.
i have added the run.sh to path so that i can run it from anywhere 

this is my current `run.sh`
```
# Get all sys args after file name
args=("$@")

source "$(dirname "$0")/venv/bin/activate"

# Run src/main.py with sys args
python "$(dirname "$0")/src/main.py" "$@"

```
for full repo you can check :[my frork](https://github.com/codewarnab/TeleSync)
### Expected Behavior:

The `run.sh` script should consistently use the same `anon.session` and `db` files, regardless of the folder it is run from. This would streamline the login process and improve usability.

### Additional Information:

- OS: Ubuntu 24.04
- Script: `run.sh`
- python -v : 3.12
- Virtual Environment: `venv`

**Comment by FujiwaraChoki** [comment]
Seems good, could you open a PR?

**Comment by codewarnab** [comment]
> Seems good, could you open a PR?

I am unable to fix the issue of multiple anon.session and db file creation ...
Tho u want me to create pr ? 

For adding to path and reproducing 

1. Edit `~/.bashrc.
2. Add `export PATH="$PATH:/path/to/your/directory"` at the end.
3. Save and exit.

**Comment by codewarnab** [comment]
@FujiwaraChoki  hey i have fixed the issue now it will create the db file and session file inside the folder only so if you run from  diffrent folders using path you dont have to login again also added support for windows and optional neon db and properly tested all the features and updated the Readme.md as well #6

**Comment by FujiwaraChoki** [comment]
Please remove the "neon.db" support, as that is limited. I would like to keep this local.

**Comment by codewarnab** [comment]
> Please remove the "neon.db" support, as that is limited. I would like to keep this local.

Ok I will

**Comment by codewarnab** [comment]
> Please remove the "neon.db" support, as that is limited. I would like to keep this local.

done check now #7 @FujiwaraChoki

**Comment by FujiwaraChoki** [comment]
=> merged.
